// chat/src/solid/core/Main.tsx
import { Sidebar } from '@s-components/sidebar';
import { Login } from '@s-components/login';
import { ChatMain } from '@s-components/chat/main';
import { useUserContext } from '@s-context/user';
import { Show } from 'solid-js';

export const Main = () => {
  const { user } = useUserContext();

  return <>
    <Sidebar />
    <Show when={!user()?.isLoggedIn}>
      <Login />
    </Show>
    <ChatMain />
  </>;
};

// chat/src/react/core/Main.tsx
import { useContext } from 'react';
import { Chat } from '@components/chat';
import { Login } from '@components/login';
import { Sidebar } from '@components/sidebar';
import { UserContext } from '@context/user';

export const Main = () => {
  const user = useContext(UserContext);

  return <>
    <Sidebar />
    <main>
      {!user.isLoggedIn ? <Login /> : <Chat />}
    </main>
  </>;
};
